### ISSUE TITLE
add an api route for retrieving annotations raw data

### ISSUE THREAD

**Issue by balmas** [perseids-project/digital_milliet#28]
We should add an api route to retrieve the raw data of the annotations (serialized as OA)

**Comment by annakrohn** [comment]
@balmas, the latest commit is a super simple dump of the JSON based on the digmill id, do we want any more than that?  Dump of full list, searching by cts urn, etc?

**Comment by balmas** [comment]
I think starting with what you have is fine.  If we want to add more later we can, but I'm happy with a per commentary download of the json for now.

**Comment by balmas** [comment]
oh, but maybe you could rename the "removethingIhate" method? Or at least explain why you hate it ? :)

**Comment by annakrohn** [comment]
Oh man, that was an attempt to remove MongoDB's BSON id, that caused no small share of headaches before I realized what was going on.  Because BSON cannot be serialized to JSON.  Supposedly pymongo fixed it and made the whole jsonify thing work again, but I couldn't get it to happen for me. 

Thank you for catching that, I thought I'd deleted it!

**Comment by annakrohn** [comment]
@balmas, I'm going to do the pull request and merge this with the iss16 branch, as that is what it came off of.
